FROM node:16

WORKDIR /app/

COPY package.json package-lock.json ./
COPY tsconfig.json tsconfig.json

RUN npm install

COPY src/ ./src/
COPY contracts contracts

RUN npm run build

ENTRYPOINT ["node" , "./dist/index.js"]

EXPOSE 8080